site:
  title: Zeent хэрэглэгчийн гарын авлага
  url: https://userguide.zeent.tech
  start_page: zeent-portal::index.adoc
  robots: allow
content:
  sources: 
  - url: .
    branches: HEAD
    start_path: zeent-portal
  - url: .
    branches: HEAD
    start_path: zeent-mobile-pos
ui: 
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
runtime:
  cache_dir: ./.cache/antora
  log:
    failure_level: warn
antora:
  extensions:
    - require: '@antora/lunr-extension'
      index_latest_only: true
      languages: [en, ru]
