site:
  title: Zeent User Guide
  url: https://docs.zeent.tech
  start_page: zeent-portal::index.adoc
  robots: allow
content:
  sources: 
  - url: .
    branches: HEAD
  - url: .
    branches: HEAD
    start_path: zeent-mobile-pos
ui: 
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
runtime:
  cache_dir: ./.cache/antora
  log:
    failure_level: warn